services:
  minecraft:
    image: marctv/minecraft-papermc-server:1.21.3
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "4G"
      PAPERMC_FLAGS: ""
    volumes:
      - /data/containers/mcserver/:/data
    ports:
      - "25565:25565"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcserver.rule=Host(`42authcraft.ruinformatique.ch`) || Host(`42authcraft.ruinfo.ch`)"
      - "traefik.http.routers.mcserver.tls=true"
      - "traefik.http.services.mcserver.loadbalancer.server.port=8080"
    networks:
      - reverse-proxy
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
networks:
  reverse-proxy:
    external: true
