services:
  ruinformatique:
    container_name: ruinformatique
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.ruinformatique.rule=Host(`www.ruinformatique.ch`) || Host(`ruinformatique.ch`)"
      - "traefik.http.routers.ruinformatique.tls=true"
    build: /home/docker/ruinformatique-www/
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
