services:
 kuma:
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`status.ruinformatique.ch`)"
      - "traefik.http.routers.kuma.tls=true"
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: always
    volumes:
      - /data/containers/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - "reverse-proxy"

networks:
  reverse-proxy:
    external: true

