services: 
  watchtower:     
    image: nickfedor/watchtower
    container_name: watchtower 
    restart: always 
    labels:
      com.centurylinklabs.watchtower.stop-signal: "SIGHUP"
    env_file:
      - ./conf/watchtower/.env
    environment:
      WATCHTOWER_SCHEDULE: "0 0 * * * *" 
      TZ: Europe/Zurich 
      WATCHTOWER_CLEANUP: "true" 
      WATCHTOWER_DEBUG: "true"      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
