version: "3.2"
services:  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - reverse-proxy
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.ruinformatique.ch`) "
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    env_file:
      - ./conf/pihole/.env
    volumes:
      - '/data/containers/pihole/etc:/etc/pihole'
      - '/data/containers/pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: always
      
networks:
  reverse-proxy:
    external: true
      #  pihole_net:
      #    driver: macvlan
      #   driver_opts: 
      #     parent: enp6s18
      #   ipam:
      #     config:
      #      - subnet: 192.168.31.0/24
      #        gateway: 192.168.31.1 
