services:
  reverse-proxy:
    container_name: traefik
    image: traefik:latest

    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entryPoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/custom.d/
      - --providers.file.watch=true
      
    ports:
      # The HTTP(S) ports
      - "443:443"

    # auto-update
    labels:
      - "com.centurylinklabs.watchtower.stop-signal=SIGHUP"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/containers/traefik/ca/:/etc/ca/
      - /data/containers/traefik/custom.d/:/etc/traefik/custom.d/
        #  - /data/traefik/whitelist/whitelist.txt:/etc/traefik/whitelist/whitelist.txt
    networks:
      - reverse-proxy
    restart: "always"

networks:
  reverse-proxy:
    driver: bridge
    name: reverse-proxy
